# Generated by Django 2.0.5 on 2018-10-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='phone_number',
            new_name='phone_number_writer',
        ),
        migrations.AddField(
            model_name='firm',
            name='phone_number_manager',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
